# Random experiments
---

A space for random stuff to happen.

In [1]:
import pandas as pd              # Pandas to handle the data in dataframes
import re                        # re to do regex searches in string data
import plotly                    # Plotly for interactive and pretty plots
import plotly.graph_objs as go
import os                        # os handles directory/workspace changes
import numpy as np               # NumPy to handle numeric and NaN operations
from tqdm import tqdm_notebook   # tqdm allows to track code execution progress
import torch                     # PyTorch to create and apply deep learning models
from torch.utils.data.sampler import SubsetRandomSampler
import shap                      # Model-agnostic interpretability package inspired on Shapley values
import pickle                    # Save python objects in files
from datetime import datetime    # datetime to use proper date and time formats
import utils                     # Contains auxiliary functions
from Time_Series_Dataset import Time_Series_Dataset # Dataset subclass which allows the creation of Dataset objects
from ModelInterpreter import ModelInterpreter # Class that enables the interpretation of models that handle variable sequence length input data

In [2]:
# Debugging packages
import pixiedust                 # Debugging in Jupyter Notebook cells
import numpy as np               # Math operations with NumPy to confirm model's behaviour
import time                      # Calculate code execution time

Pixiedust database opened successfully


## Sorting

In [33]:
x_lengths_arr = np.array(x_lengths_test)
x_lengths_arr

array([20, 18, 17, 16, 16, 16, 16, 15, 15, 15, 14, 14, 14, 13, 13, 13, 13,
       13, 12, 12, 12, 12, 12, 12, 12, 11, 11, 11, 11, 10, 10, 10, 10, 10,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2])

In [41]:
x_lengths_cum = np.cumsum(x_lengths_arr)
x_lengths_cum

array([  20,   38,   55,   71,   87,  103,  119,  134,  149,  164,  178,
        192,  206,  219,  232,  245,  258,  271,  283,  295,  307,  319,
        331,  343,  355,  366,  377,  388,  399,  409,  419,  429,  439,
        449,  459,  468,  477,  486,  495,  504,  513,  522,  531,  540,
        548,  556,  564,  572,  580,  588,  596,  604,  612,  620,  628,
        635,  642,  649,  656,  663,  670,  677,  684,  691,  698,  705,
        712,  719,  726,  732,  738,  744,  750,  756,  762,  768,  774,
        780,  786,  792,  798,  804,  810,  815,  820,  825,  830,  835,
        840,  845,  850,  855,  860,  865,  870,  875,  880,  885,  890,
        895,  899,  903,  907,  911,  915,  919,  923,  927,  931,  935,
        939,  943,  947,  951,  955,  959,  963,  967,  971,  975,  979,
        983,  987,  991,  995,  998, 1001, 1004, 1007, 1010, 1013, 1016,
       1019, 1022, 1025, 1028, 1031, 1034, 1037, 1040, 1043, 1046, 1049,
       1052, 1055, 1058, 1061, 1064, 1067, 1070, 10

In [42]:
start_idx = np.roll(x_lengths_cum, 1)
start_idx[0] = 0
start_idx

array([   0,   20,   38,   55,   71,   87,  103,  119,  134,  149,  164,
        178,  192,  206,  219,  232,  245,  258,  271,  283,  295,  307,
        319,  331,  343,  355,  366,  377,  388,  399,  409,  419,  429,
        439,  449,  459,  468,  477,  486,  495,  504,  513,  522,  531,
        540,  548,  556,  564,  572,  580,  588,  596,  604,  612,  620,
        628,  635,  642,  649,  656,  663,  670,  677,  684,  691,  698,
        705,  712,  719,  726,  732,  738,  744,  750,  756,  762,  768,
        774,  780,  786,  792,  798,  804,  810,  815,  820,  825,  830,
        835,  840,  845,  850,  855,  860,  865,  870,  875,  880,  885,
        890,  895,  899,  903,  907,  911,  915,  919,  923,  927,  931,
        935,  939,  943,  947,  951,  955,  959,  963,  967,  971,  975,
        979,  983,  987,  991,  995,  998, 1001, 1004, 1007, 1010, 1013,
       1016, 1019, 1022, 1025, 1028, 1031, 1034, 1037, 1040, 1043, 1046,
       1049, 1052, 1055, 1058, 1061, 1064, 1067, 10

In [43]:
end_idx = x_lengths_cum - 1
end_idx

array([  19,   37,   54,   70,   86,  102,  118,  133,  148,  163,  177,
        191,  205,  218,  231,  244,  257,  270,  282,  294,  306,  318,
        330,  342,  354,  365,  376,  387,  398,  408,  418,  428,  438,
        448,  458,  467,  476,  485,  494,  503,  512,  521,  530,  539,
        547,  555,  563,  571,  579,  587,  595,  603,  611,  619,  627,
        634,  641,  648,  655,  662,  669,  676,  683,  690,  697,  704,
        711,  718,  725,  731,  737,  743,  749,  755,  761,  767,  773,
        779,  785,  791,  797,  803,  809,  814,  819,  824,  829,  834,
        839,  844,  849,  854,  859,  864,  869,  874,  879,  884,  889,
        894,  898,  902,  906,  910,  914,  918,  922,  926,  930,  934,
        938,  942,  946,  950,  954,  958,  962,  966,  970,  974,  978,
        982,  986,  990,  994,  997, 1000, 1003, 1006, 1009, 1012, 1015,
       1018, 1021, 1024, 1027, 1030, 1033, 1036, 1039, 1042, 1045, 1048,
       1051, 1054, 1057, 1060, 1063, 1066, 1069, 10

In [44]:
[ref_output[start_idx[i]:end_idx[i]] for i in range(len(start_idx))]

[tensor([0.0241, 0.0444, 0.0263, 0.0514, 0.1115, 0.8774, 0.9326, 0.9680, 0.9946,
         0.9985, 0.9991, 0.9993, 0.9992, 0.9991, 0.9989, 0.9987, 0.9985, 0.9984,
         0.9983], grad_fn=<SliceBackward>),
 tensor([0.0298, 0.0827, 0.0403, 0.0410, 0.0302, 0.0275, 0.0261, 0.0278, 0.0689,
         0.0351, 0.0633, 0.0499, 0.0793, 0.0705, 0.0795, 0.1509, 0.9077],
        grad_fn=<SliceBackward>),
 tensor([0.0693, 0.4741, 0.5483, 0.9547, 0.9796, 0.9951, 0.9981, 0.9984, 0.9982,
         0.9973, 0.9968, 0.9964, 0.9970, 0.9977, 0.9983, 0.9986],
        grad_fn=<SliceBackward>),
 tensor([0.0769, 0.1367, 0.3866, 0.4503, 0.9552, 0.9766, 0.9946, 0.9987, 0.9992,
         0.9990, 0.9983, 0.9978, 0.9978, 0.9981, 0.9983],
        grad_fn=<SliceBackward>),
 tensor([0.8245, 0.8252, 0.9006, 0.9593, 0.9828, 0.9901, 0.9927, 0.9943, 0.9956,
         0.9965, 0.9972, 0.9977, 0.9980, 0.9982, 0.9983],
        grad_fn=<SliceBackward>),
 tensor([0.0169, 0.0450, 0.0221, 0.0203, 0.0181, 0.0946, 0.0992, 0.0316, 0.0092,
         0.0051, 0.0101, 0.0114, 0.0106, 0.0093, 0.0091],
        grad_fn=<SliceBackward>),
 tensor([0.0138, 0.0385, 0.0272, 0.0307, 0.0207, 0.0135, 0.0160, 0.0135, 0.0128,
         0.0167, 0.0197, 0.0192, 0.0182, 0.0199, 0.0130],
        grad_fn=<SliceBackward>),
 tensor([0.0256, 0.1090, 0.0429, 0.0415, 0.0375, 0.9270, 0.9192, 0.7453, 0.9171,
         0.9308, 0.9413, 0.9782, 0.9878, 0.9923], grad_fn=<SliceBackward>),
 tensor([0.0364, 0.1193, 0.1130, 0.1313, 0.3802, 0.7804, 0.4428, 0.9151, 0.9119,
         0.9692, 0.9882, 0.9923, 0.9933, 0.9941], grad_fn=<SliceBackward>),
 tensor([0.0374, 0.1065, 0.0931, 0.0992, 0.0953, 0.2422, 0.1219, 0.8868, 0.9466,
         0.9740, 0.9920, 0.9961, 0.9964, 0.9953], grad_fn=<SliceBackward>),
 tensor([0.0270, 0.0475, 0.0659, 0.0956, 0.0722, 0.0536, 0.0772, 0.0613, 0.0658,
         0.7449, 0.9658, 0.9862, 0.9969], grad_fn=<SliceBackward>),
 tensor([0.0194, 0.0068, 0.0413, 0.0145, 0.0119, 0.7155, 0.9472, 0.9902, 0.9979,
         0.9989, 0.9989, 0.9987, 0.9984], grad_fn=<SliceBackward>),
 tensor([0.0372, 0.1162, 0.1944, 0.4293, 0.2589, 0.9177, 0.9448, 0.9784, 0.9958,
         0.9984, 0.9989, 0.9991, 0.9992], grad_fn=<SliceBackward>),
 tensor([0.0383, 0.0980, 0.0751, 0.0902, 0.0380, 0.0592, 0.0590, 0.0914, 0.0817,
         0.8103, 0.9727, 0.9893], grad_fn=<SliceBackward>),
 tensor([0.0405, 0.0686, 0.0605, 0.1342, 0.5160, 0.6011, 0.5904, 0.5695, 0.5763,
         0.7266, 0.7777, 0.8513], grad_fn=<SliceBackward>),
 tensor([0.0183, 0.0458, 0.0568, 0.0877, 0.0486, 0.0413, 0.0368, 0.0417, 0.0447,
         0.0454, 0.0397, 0.0425], grad_fn=<SliceBackward>),
 tensor([0.0151, 0.0612, 0.0470, 0.0619, 0.0349, 0.0541, 0.0416, 0.0470, 0.0450,
         0.0442, 0.0696, 0.0615], grad_fn=<SliceBackward>),
 tensor([0.0335, 0.0367, 0.0374, 0.2127, 0.1906, 0.1431, 0.0716, 0.0706, 0.1241,
         0.2013, 0.2265, 0.2228], grad_fn=<SliceBackward>),
 tensor([0.0226, 0.0881, 0.0576, 0.0452, 0.0626, 0.0941, 0.1200, 0.8515, 0.9715,
         0.9877, 0.9968], grad_fn=<SliceBackward>),
 tensor([0.0255, 0.0576, 0.1609, 0.7596, 0.8914, 0.9380, 0.9817, 0.9940, 0.9972,
         0.9980, 0.9984], grad_fn=<SliceBackward>),
 tensor([0.0352, 0.0912, 0.0599, 0.1004, 0.0580, 0.2804, 0.4198, 0.8725, 0.9135,
         0.9490, 0.9856], grad_fn=<SliceBackward>),
 tensor([0.4554, 0.8182, 0.9204, 0.9905, 0.9978, 0.9991, 0.9992, 0.9990, 0.9985,
         0.9973, 0.9962], grad_fn=<SliceBackward>),
 tensor([0.0196, 0.0474, 0.0205, 0.0212, 0.0156, 0.0168, 0.0120, 0.0121, 0.0303,
         0.0096, 0.0127], grad_fn=<SliceBackward>),
 tensor([0.0566, 0.1972, 0.1213, 0.2309, 0.2054, 0.1986, 0.1693, 0.1249, 0.1404,
         0.1271, 0.1946], grad_fn=<SliceBackward>),
 tensor([0.0529, 0.0434, 0.0342, 0.0678, 0.0546, 0.1131, 0.1706, 0.1817, 0.0841,
         0.0430, 0.2016], grad_fn=<SliceBackward>),
 tensor([0.0822, 0.1127, 0.1335, 0.2197, 0.2912, 0.3378, 0.4718, 0.4954, 0.5350,
         0.7684], grad_fn=<SliceBackward>),
 tensor([0.0397, 0.1289, 0.2412, 0.5784, 0.9379, 0.95